class Version(object):

    @staticmethod
    def BFVer():
        return "0.0.1"

    @staticmethod
    def OFVer():
        return "3.2"


class Header(object):
    """Input files header
    Usage:
        Header.header()
    """

    @staticmethod
    def header(OpenFOAMVersion="3.2.0", ButterflyVersion="0.0.1"):
        header = "/*--------------------------------*- C++ -*----------------------------------*\\\n" + \
                 "| =========                 |                                                 |\n"  + \
                 "| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |\n" + \
                 "|  \\\\    /   O peration     | Version:  {}                                 |\n" + \
                 "|   \\\\  /    A nd           | Web:      www.OpenFOAM.org                      |\n" + \
                 "|    \\\\/     M anipulation  | Generated by: Butterfly {}                   |\n" + \
                 "|                           | https://github.com/mostaphaRoudsari/Butterfly/  |\n" + \
                 "\\*---------------------------------------------------------------------------*/\n"

        return header.format(OpenFOAMVersion, ButterflyVersion)
