# Butterfly: A Plugin for CFD Analysis (GPL) started by Mostapha Sadeghipour Roudsari
# This file is part of Butterfly.
#
# You should have received a copy of the GNU General Public License
# along with Ladybug; If not, see <http://www.gnu.org/licenses/>.
# 
# @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>

"""
Purge case folder.

-

    Args:
        _case: Butterfly case.
        _blockMesh_: Set to True to erase the files inside constant/polyMesh folder.
        _snappyHexMesh_: Set to True to remove mesh folders generated by snappyHexMesh.
        _results_: Set to True to remove result folders.
        _postProcessing_: Set to True to remove postProcessing folder.
"""

ghenv.Component.Name = "Butterfly_purgeCase"
ghenv.Component.NickName = "purgeCase"
ghenv.Component.Message = 'VER 0.0.03\nFEB_08_2017'
ghenv.Component.Category = "Butterfly"
ghenv.Component.SubCategory = "08::Etc"
ghenv.Component.AdditionalHelpFromDocStrings = "2"

if _case:
    _case.purge(_blockMesh_, _snappyHexMesh_, _results_, _postProcessing_)
else:
    print "_case input is empty."